language: node_js

node_js:
  - "12"
  - "13"
  - "node"

install:
  - "npm install"
  - "npm install @hapi/hapi@$HAPI_VERSION"

env:
  - HAPI_VERSION="17"
  - HAPI_VERSION="18"
  - HAPI_VERSION="19"

jobs:
  exclude:
    - node_js: "12"
      env: HAPI_VERSION="19"s
